# include themes/noctalia.conf

background_opacity 0.8
confirm_os_window_close 0
disable_ligatures never
enable_audio_bell no
font_family family = "FiraCode Nerd Font"
font_size 12.0
window_padding_width 8

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
